/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fodder;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.Timer;

/**
 *
 * @author DELL-15
 */

public class menuPage extends javax.swing.JFrame {

    /**
     * Creates new form menuPage
     */
    public menuPage() {
        initComponents();
        Color borderColor = new Color(179, 193, 193);
        NorthIndianLabel.setBorder(BorderFactory.createMatteBorder(0, 2, 2, 0, borderColor));
        SouthIndianLabel.setBorder(BorderFactory.createMatteBorder(0, 2, 2, 0, borderColor));
        PunjabiLabel.setBorder(BorderFactory.createMatteBorder(0, 2, 2, 0, borderColor));
        GujaratiLabel.setBorder(BorderFactory.createMatteBorder(0, 2, 2, 0, borderColor));
        proceedToPay.setBorder(BorderFactory.createMatteBorder(0, 2, 2, 0, borderColor));
        logOut.setBorder(BorderFactory.createMatteBorder(0, 2, 2, 0, borderColor));
        borderColor = new Color(101,43,215);
        FastFoodLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel33 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        MotionPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        FastFoodLabel = new javax.swing.JLabel();
        NorthIndianLabel = new javax.swing.JLabel();
        SouthIndianLabel = new javax.swing.JLabel();
        PunjabiLabel = new javax.swing.JLabel();
        GujaratiLabel = new javax.swing.JLabel();
        proceedToPay = new javax.swing.JLabel();
        logOut = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        FastFoodPanel = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel33.setBackground(new java.awt.Color(101, 43, 215));

        jLabel1.setFont(new java.awt.Font("CAC Champagne", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 239, 239));
        jLabel1.setText("fodder");

        exit.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        exit.setForeground(new java.awt.Color(239, 239, 239));
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        min.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        min.setForeground(new java.awt.Color(239, 239, 239));
        min.setText("-");
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });

        JPanel MotionPanel = new MotionPanel(this);
        MotionPanel.setBackground(new java.awt.Color(101, 43, 215));

        javax.swing.GroupLayout MotionPanelLayout = new javax.swing.GroupLayout(MotionPanel);
        MotionPanel.setLayout(MotionPanelLayout);
        MotionPanelLayout.setHorizontalGroup(
            MotionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MotionPanelLayout.setVerticalGroup(
            MotionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 523, Short.MAX_VALUE)
                .addComponent(min)
                .addGap(18, 18, 18)
                .addComponent(exit)
                .addGap(20, 20, 20))
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MotionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addComponent(MotionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(exit)
                    .addComponent(min))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        FastFoodLabel.setBackground(new java.awt.Color(239, 239, 239));
        FastFoodLabel.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        FastFoodLabel.setForeground(new java.awt.Color(101, 43, 215));
        FastFoodLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FastFoodLabel.setText("Fast Food");
        FastFoodLabel.setOpaque(true);
        FastFoodLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FastFoodLabelMouseClicked(evt);
            }
        });

        NorthIndianLabel.setBackground(new java.awt.Color(239, 239, 239));
        NorthIndianLabel.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        NorthIndianLabel.setForeground(new java.awt.Color(101, 43, 215));
        NorthIndianLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NorthIndianLabel.setText("North Indian");
        NorthIndianLabel.setOpaque(true);
        NorthIndianLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NorthIndianLabelMouseClicked(evt);
            }
        });

        SouthIndianLabel.setBackground(new java.awt.Color(239, 239, 239));
        SouthIndianLabel.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        SouthIndianLabel.setForeground(new java.awt.Color(101, 43, 215));
        SouthIndianLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SouthIndianLabel.setText("South Indian");
        SouthIndianLabel.setOpaque(true);
        SouthIndianLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SouthIndianLabelMouseClicked(evt);
            }
        });

        PunjabiLabel.setBackground(new java.awt.Color(239, 239, 239));
        PunjabiLabel.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        PunjabiLabel.setForeground(new java.awt.Color(101, 43, 215));
        PunjabiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PunjabiLabel.setText("Punjabi");
        PunjabiLabel.setOpaque(true);
        PunjabiLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PunjabiLabelMouseClicked(evt);
            }
        });

        GujaratiLabel.setBackground(new java.awt.Color(239, 239, 239));
        GujaratiLabel.setFont(new java.awt.Font("Chaparral Pro Light", 0, 18)); // NOI18N
        GujaratiLabel.setForeground(new java.awt.Color(101, 43, 215));
        GujaratiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GujaratiLabel.setText("Gujarati");
        GujaratiLabel.setMaximumSize(new java.awt.Dimension(26, 16));
        GujaratiLabel.setMinimumSize(new java.awt.Dimension(26, 16));
        GujaratiLabel.setOpaque(true);
        GujaratiLabel.setPreferredSize(new java.awt.Dimension(26, 16));
        GujaratiLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GujaratiLabelMouseClicked(evt);
            }
        });

        proceedToPay.setBackground(new java.awt.Color(153, 255, 153));
        proceedToPay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proceedToPay.setText("Proceed to Pay");
        proceedToPay.setOpaque(true);

        logOut.setBackground(new java.awt.Color(153, 255, 153));
        logOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logOut.setText("Log Out");
        logOut.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(NorthIndianLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(SouthIndianLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(520, 520, 520)
                        .addComponent(proceedToPay, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(FastFoodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(PunjabiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(GujaratiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NorthIndianLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(SouthIndianLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(proceedToPay, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(FastFoodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(PunjabiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(GujaratiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        menuPanel.setBackground(new java.awt.Color(239, 239, 239));
        menuPanel.setLayout(new java.awt.CardLayout());

        FastFoodPanel.setBackground(new java.awt.Color(239, 239, 239));

        jPanel18.setBackground(new java.awt.Color(239, 239, 239));

        jLabel2.setBackground(new java.awt.Color(239, 239, 239));
        jLabel2.setFont(new java.awt.Font("Avenir LT Std 55 Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu");

        jPanel5.setBackground(new java.awt.Color(239, 239, 239));

        jLabel6.setBackground(new java.awt.Color(239, 239, 239));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hakka Noodles");
        jLabel6.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(239, 239, 239));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Golden Stir Fried Babycorn");
        jLabel7.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(239, 239, 239));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Regular Pizza");
        jLabel8.setOpaque(true);

        jLabel9.setBackground(new java.awt.Color(239, 239, 239));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Cheese Chilly");
        jLabel9.setOpaque(true);

        jLabel10.setBackground(new java.awt.Color(239, 239, 239));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Continental Sizzler");
        jLabel10.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(239, 239, 239));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Price");

        jPanel6.setBackground(new java.awt.Color(239, 239, 239));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("160");
        jLabel11.setOpaque(true);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("180");
        jLabel12.setOpaque(true);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("250");
        jLabel13.setOpaque(true);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("250");
        jLabel14.setOpaque(true);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("350");
        jLabel15.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(239, 239, 239));

        jPanel7.setBackground(new java.awt.Color(239, 239, 239));

        jSpinner1.setPreferredSize(new java.awt.Dimension(29, 14));

        jSpinner2.setPreferredSize(new java.awt.Dimension(29, 14));

        jSpinner3.setPreferredSize(new java.awt.Dimension(29, 14));

        jSpinner4.setPreferredSize(new java.awt.Dimension(29, 14));

        jSpinner5.setPreferredSize(new java.awt.Dimension(29, 14));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSpinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Quantity");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout FastFoodPanelLayout = new javax.swing.GroupLayout(FastFoodPanel);
        FastFoodPanel.setLayout(FastFoodPanelLayout);
        FastFoodPanelLayout.setHorizontalGroup(
            FastFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FastFoodPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        FastFoodPanelLayout.setVerticalGroup(
            FastFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FastFoodPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(FastFoodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPanel.add(FastFoodPanel, "FastFoodCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel33, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FastFoodLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FastFoodLabelMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(this.menuPanel.getLayout());
        cl.show(this.menuPanel, "FastFoodCard");
        Color borderColor = new Color(179, 193, 193);
        NorthIndianLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        SouthIndianLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        PunjabiLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        GujaratiLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        proceedToPay.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        logOut.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        borderColor = new Color(101,43,215);
        FastFoodLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
    }//GEN-LAST:event_FastFoodLabelMouseClicked

    private void NorthIndianLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NorthIndianLabelMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(this.menuPanel.getLayout());
        cl.show(this.menuPanel, "NorthIndianCard");
        Color borderColor = new Color(179, 193, 193);
        FastFoodLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        SouthIndianLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        PunjabiLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        GujaratiLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        proceedToPay.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        logOut.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        borderColor = new Color(101,43,215);
        NorthIndianLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
    }//GEN-LAST:event_NorthIndianLabelMouseClicked

    private void SouthIndianLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SouthIndianLabelMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(this.menuPanel.getLayout());
        cl.show(this.menuPanel, "SouthIndianCard");
        Color borderColor = new Color(179, 193, 193);
        NorthIndianLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        FastFoodLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        PunjabiLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        GujaratiLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        proceedToPay.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        logOut.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        borderColor = new Color(101,43,215);
        SouthIndianLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
    }//GEN-LAST:event_SouthIndianLabelMouseClicked

    private void PunjabiLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PunjabiLabelMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(this.menuPanel.getLayout());
        cl.show(this.menuPanel, "PunjabiCard");
        Color borderColor = new Color(179, 193, 193);
        NorthIndianLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        SouthIndianLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        FastFoodLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        GujaratiLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        proceedToPay.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        logOut.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        borderColor = new Color(101,43,215);
        PunjabiLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
    }//GEN-LAST:event_PunjabiLabelMouseClicked

    private void GujaratiLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GujaratiLabelMouseClicked
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(this.menuPanel.getLayout());
        cl.show(this.menuPanel, "GujaratiCard");
        Color borderColor = new Color(179, 193, 193);
        NorthIndianLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        SouthIndianLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        PunjabiLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        FastFoodLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        proceedToPay.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        logOut.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
        borderColor = new Color(101,43,215);
        GujaratiLabel.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, borderColor));
    }//GEN-LAST:event_GujaratiLabelMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        // TODO add your handling code here:
        exit.setForeground(Color.RED);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        // TODO add your handling code here:
        exit.setForeground(Color.WHITE);
    }//GEN-LAST:event_exitMouseExited

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FastFoodLabel;
    private javax.swing.JPanel FastFoodPanel;
    private javax.swing.JLabel GujaratiLabel;
    private javax.swing.JPanel MotionPanel;
    private javax.swing.JLabel NorthIndianLabel;
    private javax.swing.JLabel PunjabiLabel;
    private javax.swing.JLabel SouthIndianLabel;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JLabel logOut;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel min;
    private javax.swing.JLabel proceedToPay;
    // End of variables declaration//GEN-END:variables
}
