/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fodder;

import Backend.Customer;
import Backend.FoodItem;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Himank Goel
 */
public class PaymentPage extends javax.swing.JFrame {
    Customer customer;
    
    /**
     * Creates new form PaymentPage
     */
    public PaymentPage(Customer customer) {
        this.customer = customer;
        initComponents();
        logoSetup();
        this.setLocationRelativeTo(null);
        
        jTextArea1.append("\t          Order\n");
        
        for (FoodItem item : customer.getCart()) {
            int totalPrice = item.getPrice() * item.getQuantity();
            jTextArea1.append(item.getName() + "  : " + item.getQuantity() + " pcs  : Rs." + totalPrice + "\n");
        }
        
        jTextArea1.append("\n");
        for (int i = 0; i < 54; i++) {
            jTextArea1.append("-");
        }
        
        jTextArea1.append("\n\nPrice\n\nTotal Price : Rs." + customer.getTotalPrice() 
                + "\nTax (GST 18%) : Rs." + customer.getTax() + "\nTotal Amount : Rs." + customer.getTaxedPrice());
    }
    
    private void logoSetup() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        MotionPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        firstChoice = new javax.swing.JPanel();
        dineIn = new javax.swing.JButton();
        homeDelivery = new javax.swing.JButton();
        deliveryChoices = new javax.swing.JPanel();
        debitCard = new javax.swing.JButton();
        creditCard = new javax.swing.JButton();
        cod = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(101, 43, 215));

        jLabel1.setFont(new java.awt.Font("CAC Champagne", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(239, 239, 239));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fodder/logo-small.png"))); // NOI18N
        jLabel1.setText("fodder");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        exit.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        exit.setForeground(new java.awt.Color(239, 239, 239));
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        min.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        min.setForeground(new java.awt.Color(239, 239, 239));
        min.setText("-");
        min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minMouseClicked(evt);
            }
        });

        JPanel MotionPanel = new MotionPanel(this);
        MotionPanel.setBackground(new java.awt.Color(101, 43, 215));

        javax.swing.GroupLayout MotionPanelLayout = new javax.swing.GroupLayout(MotionPanel);
        MotionPanel.setLayout(MotionPanelLayout);
        MotionPanelLayout.setHorizontalGroup(
            MotionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MotionPanelLayout.setVerticalGroup(
            MotionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(min)
                        .addGap(18, 18, 18)
                        .addComponent(exit)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MotionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(MotionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(exit)
                    .addComponent(min))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(239, 239, 239));

        jTextArea1.setBackground(new java.awt.Color(239, 239, 239));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Avenir LT Std 45 Book", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setEditable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.setBackground(new java.awt.Color(239, 239, 239));
        jPanel3.setLayout(new java.awt.CardLayout());

        firstChoice.setBackground(new java.awt.Color(239, 239, 239));

        dineIn.setBackground(new java.awt.Color(101, 43, 215));
        dineIn.setForeground(new java.awt.Color(239, 239, 239));
        dineIn.setText("Dine In !");
        dineIn.setPreferredSize(new java.awt.Dimension(115, 25));
        dineIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dineInMouseClicked(evt);
            }
        });
        dineIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dineInActionPerformed(evt);
            }
        });

        homeDelivery.setBackground(new java.awt.Color(101, 43, 215));
        homeDelivery.setForeground(new java.awt.Color(239, 239, 239));
        homeDelivery.setText("Home Delivery");
        homeDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeDeliveryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout firstChoiceLayout = new javax.swing.GroupLayout(firstChoice);
        firstChoice.setLayout(firstChoiceLayout);
        firstChoiceLayout.setHorizontalGroup(
            firstChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstChoiceLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(dineIn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(homeDelivery)
                .addGap(50, 50, 50))
        );
        firstChoiceLayout.setVerticalGroup(
            firstChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstChoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(homeDelivery, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(dineIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.add(firstChoice, "card2");

        deliveryChoices.setBackground(new java.awt.Color(239, 239, 239));

        debitCard.setBackground(new java.awt.Color(101, 43, 215));
        debitCard.setForeground(new java.awt.Color(239, 239, 239));
        debitCard.setText("Debit Card");
        debitCard.setPreferredSize(new java.awt.Dimension(115, 25));
        debitCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                debitCardMouseClicked(evt);
            }
        });
        debitCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitCardActionPerformed(evt);
            }
        });

        creditCard.setBackground(new java.awt.Color(101, 43, 215));
        creditCard.setForeground(new java.awt.Color(239, 239, 239));
        creditCard.setText("Credit Card");
        creditCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditCardActionPerformed(evt);
            }
        });

        cod.setBackground(new java.awt.Color(101, 43, 215));
        cod.setForeground(new java.awt.Color(239, 239, 239));
        cod.setText("COD");
        cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deliveryChoicesLayout = new javax.swing.GroupLayout(deliveryChoices);
        deliveryChoices.setLayout(deliveryChoicesLayout);
        deliveryChoicesLayout.setHorizontalGroup(
            deliveryChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryChoicesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(debitCard, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(creditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deliveryChoicesLayout.setVerticalGroup(
            deliveryChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deliveryChoicesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deliveryChoicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(debitCard, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(creditCard, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(cod, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.add(deliveryChoices, "deliveryCard");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        // TODO add your handling code here:
        exit.setForeground(Color.RED);
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        // TODO add your handling code here:
        exit.setForeground(Color.WHITE);
    }//GEN-LAST:event_exitMouseExited

    private void minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minMouseClicked

    private void dineInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dineInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dineInActionPerformed

    private void homeDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeDeliveryActionPerformed
        // TODO add your handling code here:
        CardLayout c1 = (CardLayout) jPanel3.getLayout();
        c1.show(jPanel3, "deliveryCard");
    }//GEN-LAST:event_homeDeliveryActionPerformed

    private void dineInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dineInMouseClicked
        // TODO add your handling code here:
        Random r = new Random( System.currentTimeMillis() );
        int a = 10000 + r.nextInt(20000);
        jTextArea1.setText("Your order has been recieved by us" + "\n" + "Your token number is " + a + "\n\nHappy Dining");
        dineIn.setEnabled(false);
        homeDelivery.setEnabled(false);
    }//GEN-LAST:event_dineInMouseClicked

    private void debitCardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_debitCardMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_debitCardMouseClicked

    private void debitCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitCardActionPerformed
        Random r = new Random(System.currentTimeMillis());
        int a = r.nextInt(4000);
        jTextArea1.setText("Used saved Debit Card : \nCard Number: XXXX XXXX XXXX " + a + "\nAccount Holder's name: " + customer.getName());
        creditCard.setEnabled(false);
        debitCard.setEnabled(false);
        cod.setEnabled(false);
    }//GEN-LAST:event_debitCardActionPerformed

    private void creditCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditCardActionPerformed
        Random r = new Random(System.currentTimeMillis());
        int a = r.nextInt(4000);
        jTextArea1.setText("Used saved Credit Card : \nCard Number: XXXX XXXX XXXX " + a +"\nAccount Holder's name: " + customer.getName());
        creditCard.setEnabled(false);
        debitCard.setEnabled(false);
        cod.setEnabled(false);
    }//GEN-LAST:event_creditCardActionPerformed

    private void codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codActionPerformed
        jTextArea1.setText("Your order is on it's way.\nAn invoice has been sent to your registered \n email address.\nEmail: " + customer.getEmail() 
                + "\n\nPlease show it to the delivery boy");
        creditCard.setEnabled(false);
        debitCard.setEnabled(false);
        cod.setEnabled(false);
    }//GEN-LAST:event_codActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new menuPage(customer).setVisible(true); 
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PaymentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PaymentPage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MotionPanel;
    private javax.swing.JButton cod;
    private javax.swing.JButton creditCard;
    private javax.swing.JButton debitCard;
    private javax.swing.JPanel deliveryChoices;
    private javax.swing.JButton dineIn;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel firstChoice;
    private javax.swing.JButton homeDelivery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel min;
    // End of variables declaration//GEN-END:variables
}
